apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
      app: myapp
      type: front-end
spec:
  # nodeName: node01 # Assign pod to specific node
  containers:
    - name: nginx-container
      image: nginx
