apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3
