apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: nginx # Deben ser los labels del pod
    type: front-end # Deben ser los labels del pod
